export const tasks = [
    {
        id: 'task1',
        title: 'SKT',
        keywords: 16,
        dataPoints: 14,
        percentage: 9,
        startDate: '2025-05-13',
        endDate: '2025-05-28',
        tags: ['폴더블', '프리미엄 시장', '반도체', '스마트폰'],
    },
    // {
    //     id: 'task2',
    //     title: '양자컴퓨팅',
    //     keywords: 10,
    //     dataPoints: 6251,
    //     percentage: 85,
    //     startDate: '2025-04-14',
    //     endDate: '2025-04-26',
    //     tags: ['IBM', '양자암호화', '양자우위', '구글'],
    // },

    // {
    //     id: 'task4',
    //     title: '구글',
    //     keywords: 10,
    //     dataPoints: 6251,
    //     percentage: 85,
    //     startDate: '2025-02-25',
    //     endDate: '2025-04-05',
    //     tags: ['IBM', '양자암호화', '양자우위', '구글'],
    // },
    // {
    //     id: 'task5',
    //     title: 'IT',
    //     keywords: 10,
    //     dataPoints: 6251,
    //     percentage: 85,
    //     startDate: '2025-02-25',
    //     endDate: '2025-03-15',
    //     tags: ['IBM', '양자암호화', '양자우위', '구글'],
    // },
]
